import { describe, expect, it } from 'vitest';

import type { BufferItem } from '../types';
import { getAlchemySearchText, removeLocalAlchemyKeywords } from './alchemy';

const createItem = (patch: Partial<BufferItem>): BufferItem => ({
  id: 'item-1',
  type: 'image',
  content: 'generated image',
  createdAt: 1,
  ...patch,
});

describe('drawer search text', () => {
  it('does not index notes attached to images', () => {
    const searchText = getAlchemySearchText(createItem({
      remark: 'private generation prompt',
      remarks: ['another prompt note'],
    }));

    expect(searchText).not.toContain('private generation prompt');
    expect(searchText).not.toContain('another prompt note');
  });

  it('still indexes notes for non-image drawer items', () => {
    const searchText = getAlchemySearchText(createItem({
      type: 'text',
      remark: 'searchable note',
    }));

    expect(searchText).toContain('searchable note');
  });

  it('does not index keywords generated by the local analysis algorithm', () => {
    const searchText = getAlchemySearchText(createItem({
      alchemy: {
        state: 'alchemy',
        result: {
          colors: ['#111111'],
          keywords: ['local-only-tag'],
          form: '',
          cmf: '',
          borrow: [],
          avoid: [],
          materials: [],
          analysisMode: 'palette',
        },
      },
    }));

    expect(searchText).not.toContain('local-only-tag');
  });

  it('keeps real AI analysis keywords searchable', () => {
    const searchText = getAlchemySearchText(createItem({
      alchemy: {
        state: 'alchemy',
        result: {
          colors: ['#222222'],
          keywords: ['ai-only-tag'],
          form: '',
          cmf: '',
          borrow: [],
          avoid: [],
          materials: [],
          analysisMode: 'ai',
        },
      },
    }));

    expect(searchText).toContain('ai-only-tag');
  });

  it('indexes new AI tags without indexing image notes', () => {
    const searchText = getAlchemySearchText(createItem({
      remark: 'hidden image prompt',
      inspirationProfile: {
        itemId: 'item-1',
        summary: 'AI result',
        objects: [],
        category: '',
        form: { silhouette: [], geometry: [], proportion: [] },
        cmf: { colors: [], materials: [], finishes: [] },
        style: [],
        interaction: [],
        scene: [],
        mood: [],
        userTags: [],
        userNotes: [],
        aiTags: [{ name: 'minimal-ai-tag', category: '风格', confidence: 0.92 }],
      },
    }));

    expect(searchText).toContain('minimal-ai-tag');
    expect(searchText).not.toContain('hidden image prompt');
  });

  it('removes only local keywords while preserving colors and AI tags', () => {
    const item = createItem({
      inspirationProfile: {
        itemId: 'item-1',
        summary: 'AI result',
        objects: [],
        category: '',
        form: { silhouette: [], geometry: [], proportion: [] },
        cmf: { colors: [], materials: [], finishes: [] },
        style: [],
        interaction: [],
        scene: [],
        mood: [],
        userTags: [],
        userNotes: [],
        aiTags: [{ name: 'minimalism', category: '风格', confidence: 0.9 }],
      },
      alchemy: {
        state: 'alchemy',
        result: {
          colors: ['#333333'],
          keywords: ['legacy-local-tag'],
          form: '',
          cmf: '',
          borrow: [],
          avoid: [],
          materials: [],
          analysisMode: 'local',
        },
      },
    });

    const cleaned = removeLocalAlchemyKeywords(item);

    expect(cleaned.alchemy?.result?.keywords).toEqual([]);
    expect(cleaned.alchemy?.result?.colors).toEqual(['#333333']);
    expect(cleaned.inspirationProfile?.aiTags?.[0]?.name).toBe('minimalism');
  });
});
